using System.Threading.Tasks;
using Foaas.Client.Responses;

namespace Foaas.Client
{
    public interface IFoaasClient
    {
        Task<FoaasResponse> Version();
        Task<FoaasOperationsResponse> Operations();
        Task<FoaasResponse> Anyway(string company, string from);
        Task<FoaasResponse> Asshole(string from);
        Task<FoaasResponse> Awesome(string from);
        Task<FoaasResponse> Back(string name, string from);
        Task<FoaasResponse> Ballmer(string name, string company, string from);
        Task<FoaasResponse> Birthday(string name, string from);
        Task<FoaasResponse> Because(string from);
        Task<FoaasResponse> Blackadder(string name, string from);
        Task<FoaasResponse> Bucket(string from);
        Task<FoaasResponse> Bm(string name, string from);
        Task<FoaasResponse> Bus(string name, string from);
        Task<FoaasResponse> Bye(string from);
        Task<FoaasResponse> CanIUse(string tool, string from);
        Task<FoaasResponse> Chainsaw(string name, string from);
        Task<FoaasResponse> Cocksplat(string name, string from);
        Task<FoaasResponse> Cool(string from);
        Task<FoaasResponse> Cup(string from);
        Task<FoaasResponse> Dalton(string name, string from);
        Task<FoaasResponse> Deraadt(string name, string from);
        Task<FoaasResponse> Diabetes(string from);
        Task<FoaasResponse> Donut(string name, string from);
        Task<FoaasResponse> Donut(string @do, string something, string from);
        Task<FoaasResponse> Equity(string name, string from);
        Task<FoaasResponse> Even(string from);
        Task<FoaasResponse> Everyone(string from);
        Task<FoaasResponse> Everything(string from);
        Task<FoaasResponse> Family(string from);
        Task<FoaasResponse> Fascinating(string from);
        Task<FoaasResponse> Fewer(string name, string from);
        Task<FoaasResponse> Field(string name, string from, string reference);
        Task<FoaasResponse> Flying(string from);
        Task<FoaasResponse> FTFY(string from);
        Task<FoaasResponse> FTS(string from);
        Task<FoaasResponse> GFY(string from);
        Task<FoaasResponse> Give(string from);
        Task<FoaasResponse> Greed(string noun, string from);
        Task<FoaasResponse> HolyGrail(string from);
        Task<FoaasResponse> Horse(string from);
        Task<FoaasResponse> Idea(string from);
        Task<FoaasResponse> Immensity(string from);
        Task<FoaasResponse> FYYFF(string from);
        Task<FoaasResponse> JingleBells(string from);
        Task<FoaasResponse> Keep(string name, string from);
        Task<FoaasResponse> KeepCalm(string reaction, string from);
        Task<FoaasResponse> King(string name, string from);
        Task<FoaasResponse> Ing(string name, string from);
        Task<FoaasResponse> Life(string from);
        Task<FoaasResponse> Linus(string name, string from);
        Task<FoaasResponse> Logs(string from);
        Task<FoaasResponse> Look(string name, string from);
        Task<FoaasResponse> Looking(string from);
        Task<FoaasResponse> Legend(string name, string from);
        Task<FoaasResponse> Madison(string name, string from);
        Task<FoaasResponse> Maybe(string name, string from);
        Task<FoaasResponse> Me(string name);
        Task<FoaasResponse> Mornin(string name);
        Task<FoaasResponse> No(string name);
        Task<FoaasResponse> Off(string name, string from);
        Task<FoaasResponse> OffWith(string behaviour, string from);
        Task<FoaasResponse> Outside(string name, string from);
        Task<FoaasResponse> Particular(string thing, string from);
        Task<FoaasResponse> Pink(string from);
        Task<FoaasResponse> Problem(string name, string from);
        Task<FoaasResponse> Programmer(string from);
        Task<FoaasResponse> Nugget(string name, string from);
        Task<FoaasResponse> Pulp(string language, string from);
        Task<FoaasResponse> Question(string from);
        Task<FoaasResponse> Ratsarse(string from);
        Task<FoaasResponse> Retard(string from);
        Task<FoaasResponse> Ridiculous(string from);
        Task<FoaasResponse> Rockstar(string name, string from);
        Task<FoaasResponse> RTFM(string from);
        Task<FoaasResponse> Sake(string from);
        Task<FoaasResponse> Shakespeare(string name, string from);
        Task<FoaasResponse> Shit(string from);
        Task<FoaasResponse> ShutUp(string name, string from);
        Task<FoaasResponse> Single(string from);
        Task<FoaasResponse> Thanks(string from);
        Task<FoaasResponse> That(string from);
        Task<FoaasResponse> Think(string name, string from);
        Task<FoaasResponse> Thinking(string name, string from);
        Task<FoaasResponse> This(string from);
        Task<FoaasResponse> Thumbs(string name, string from);
        Task<FoaasResponse> Too(string from);
        Task<FoaasResponse> Tucker(string from);
        Task<FoaasResponse> What(string from);
        Task<FoaasResponse> Xmas(string name, string from);
        Task<FoaasResponse> Yoda(string name, string from);
        Task<FoaasResponse> You(string name, string from);
        Task<FoaasResponse> Zayn(string from);
        Task<FoaasResponse> Zero(string from);
        Task<FoaasResponse> Waste(string name, string from);
    }
}